name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/microsoft/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Environment
      run: |
        cat <<EOF >>$GITHUB_ENV
        VersionSuffix=alpha1-build$(printf 00000${{ github.run_number }} | tail -c 5)
        RepositoryBranch=${{ github.ref }}
        RepositoryCommit=${{ github.sha }}
        EOF
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-restore --configuration Release --output pkg
    - name: Push
      run: find pkg -name *.nupkg | xargs -I {} dotnet nuget push {}
